import Head from "next/head";
import HomeContent from "./components/HomeContent";
import AboutContent from "./components/AboutContent";
import ProjectsContent from "./components/ProjectsContent"
import FormContent from "./components/FormContent"

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HomeContent />
			<AboutContent />
			<ProjectsContent />
			<FormContent />
		</>
	);
}
