import Head from "next/head";
import HomeContent from "./components/HomeContent";
import AboutContent from "./components/AboutContent";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HomeContent />
			<AboutContent />
		</>
	);
}
